### PR TITLE
Rework Appveyor's caching

### PR DESCRIPTION
**Pull request by marsupial**
## Description
Move away from Appveyor's internal caching which is a bit too opaque, fails often, and makes it difficult to test more than one setup/compiler on Windows.

This is accomplished by reserving a branch named **appveyor** which when built will upload the dependencies into GitHub's **Release** page.

Since the deps are built on the **appveyor** branch, changes to dependencies and building up the cache can be isolated from **master**.

This PR has a few steps before it should be integrated:
Generate an OAuth token for the imageworks Github account.
Encrypt the token here: https://ci.appveyor.com/tools/encrypt
Replace the current token on line 231 of appveyor.yml
Commit into imageworks/appveyor and make sure the dependencies are built/deployed
Commit into imageworks/master

Example of how/where the binary-dependencies are stored:
https://github.com/marsupial/OpenShadingLanguage/releases/tag/WindowsDependencies

## Tests
Per #851, disabled 4 tests on VisualStudio-2017
render-cornell
render-oren-nayar
render-veachmis
render-ward

## Checklist:

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [x] I have previously submitted a [Contributor License Agreement](http://opensource.imageworks.com/cla/).
- [x] I have updated the documentation, if applicable.
- [x] I have ensured that the change is tested somewhere in the testsuite (adding new test cases if necessary).
- [x] My code follows the prevailing code style of this project.

### CODE REVIEW

**Comment by lgritz** [comment]
This is really interesting!

So the basic idea is that the builds will try to retrieve precompiled versions of the expensive dependencies, presuming that they have been stored on the GH releases page for the imageworks/OpenShadingLanguage repo? And if not found will try to build from scratch (which we know is iffy, in terms of total time)? And the magical way to create or update the set of prebuilt packages is simply to force a build from the "appveyor" branch by the main account holder (imageworks, i.e. me)?

Do I have that right?

And to seed the process, I'll need to set up the encrypted token first, yes? 

And the safeguard is that the update of the binary assets will ONLY happen when when the appveyor job runs from my account?

**Comment by marsupial** [comment]
Sounds right.
Though, I'm not sure the specifics of whether anyone with commit access to the repo or only the main account holder will trigger deployment (I'd assume the later).

**Comment by lgritz** [comment]
Even if it's anybody with commit access, that's fine. I just want to be sure some other rando can't push a broken version.

**Comment by lgritz** [comment]
OAuth token -- do I have to "register an application" first? If so, what should I put in the fields?

**Comment by marsupial** [comment]
**Personal access tokens** -> **Generate New Token**
Deployment works with the **public_repo** (Access public repositories) checked.

**Comment by lgritz** [comment]
I'm going to close this because our aim is to abandon appveyor in favor of using GitHub CI even on Windows.

**Pull request closed without merging**
