### PR TITLE
Add cube root function to the language

### PR DESCRIPTION
**Pull request by fpsunflower**
Language was missing cbrt(x) which is part of the C99 math library.

Also added a special case to allow pow(x,1.0/3.0) to be automatically turned into cbrt during runtime optimziation.

### CODE REVIEW

**Comment by fpsunflower** [comment]
The CI seems to be having trouble checking out my branch.

Did I do something wrong on my end?

**Comment by lgritz** [comment]
Temp github glitch? I'll give it a while and then re-kick the CI tests.

**Comment by fpsunflower** [comment]
Added a few lines to the testsuite.

Getting a different set of errors in CI now, though again it seems unrelated to this patch.

**Comment by lgritz** [comment]
The CI errors are surely not related to your changes. I'll look into that separately. Could be a temporary problem on github's end, or something temporarily down at llvm.org (the one I looked at had trouble with an llvm download).

**Comment by lgritz** [comment]
Oh, I see, some are having an error in testsuite/function-redef.

That's because of your change! Your additional line in stdosl.h changed the line number reported in an error message.

**Comment by lgritz** [comment]
Just run the testsuite on your end, it should be easily to update that one ref output.

**Comment by fpsunflower** [comment]
I think its all good now. The two CI failures seem unrelated to me (unless I'm missing something else).

**Comment by lgritz** [comment]
I think those are unrelated, I'm looking at them separately. Merging.

**Comment by lgritz** [comment]
As an aside, it's probably worth starting to use `git commit -s` to attach your DCO sign-off. Once the repo finally moves, PRs won't be able to merge without them. May as well establish the habit while there's stll not yet any penalty for forgetting.

**Comment by fpsunflower** [comment]
Ah I was wondering what that was about! :)

**Pull request merged**
