### PR TITLE
Add all testoptix functionality to testrender

### PR DESCRIPTION
**Pull request by lgritz**
This attempts to merge them. In the process, it's a pretty big overhaul
of the internal organization of testrender, a lot of stuff moves around
between files and classes are refactored significantly.

In subsequent PRs, we'll reconcile with Roman's texture work, and
eventually remove testoptix entirely.

### CODE REVIEW

**Comment by lgritz** [comment]
Don't look too hard at this yet; I'm going to rebase it as much as possible on Roman's recent work and submit an update.

**Comment by lgritz** [comment]
Updated. I stand by this review as a good intermediate point between mine and Roman's.

Current status:

* Roman's cut of testoptix still works, though using a bunch of files that have been merged and are now in testrender. And also I refactored a bunch of his work just to make my diffing easier.

* testrender works as always, plus does everything testoptix could do before Roman's last merge.

* As soon as I'm back in a week, I will have another PR that will fully reconcile the two and then testoptix will be retired.

Please nobody touch testrender or testoptix while I'm still in the middle of the big refactor!

**Comment by lgritz** [comment]
Comments? I'd like to merge this as soon as I return at the beginning of next week, then immediately move on to the next set of planned changes.

**Comment by fpsunflower** [comment]
LGTM!

**Pull request merged**
