### PR TITLE
Fix llvm7

### PR DESCRIPTION
**Pull request by Lucretia**
## Description

Provides 2 patches to build on current master of LLVM.

## Tests

None

## Checklist:

- [ ] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [ ] I have previously submitted a [Contributor License Agreement](http://opensource.imageworks.com/cla/).
- [ ] I have updated the documentation, if applicable.
- [ ] I have ensured that the change is tested somewhere in the testsuite (adding new test cases if necessary).
- [ ] My code follows the prevailing code style of this project.

### CODE REVIEW

**Comment by lgritz** [comment]
LGTM!

Any chance you can send me a signed CLA?

**Comment by lgritz** [comment]
> "For something so trivial??"  

If I owned the project personally, certainly, I could make the call that short contributions like this don't need a CLA. But this project is sponsored by a company that is very legally conservative about this kind of thing. They give me remarkable freedom to administer this project as I see fit -- including developing the whole thing in public and giving away every last bit of it -- and almost the only restriction they stipulate is that I not do any merges into the repo without a CLA on file from the contributor. Given how open the whole project is (and that they pay my salary), it seems like a very small concession.

> I don't have a working printer right now.

It's the same bit pattern if you paste a signature image onto the PDF and then email it to us, as if you printed, signed, re-scanned, and then emailed. There's no need to do it the hard way.

I'll look into your suggestion for  https://cla-assistant.io/
That's an interesting long-term solution, but I would expect it to take weeks or months of back and forth with the lawyers to decide if that's an adequate substitute. The gears turn slowly in big companies.

**Comment by Lucretia** [comment]
Do I just need to sign and have my name printed on it? I'm not sticking an address on it.

**Comment by Lucretia** [comment]
P.S :  My signature's pretty crap and changes all the time, an X would just as good ;)

**Comment by lgritz** [comment]
It doesn't go anywhere public. Nobody will see your address.

We just file it away and don't make any attempt to verify what your signature looks like or where you live. We trust you to fill it out as completely and seriously as you would for any other legal document.

**Comment by lgritz** [comment]
Closing. This doesn't fully work and I'll do it myself.

**Pull request closed without merging**
