### PR TITLE
Add Pixel magnifier

### PR DESCRIPTION
**Pull request by marsupial**
Still a bit messy, but does the job.
Slider is in there to either provide a clamp/normalization or choose magnification level.
Does neither yet, so dealer's choice.

### CODE REVIEW

**Comment by lgritz** [comment]
This is neat. But I'm also in the process of adding ways for users to interact with the image, including with the mouse, and maybe you don't want that other stuff in the way. I'm thinking that this "zoom/inspect" functionality ought to be something you can toggle. Maybe it is only there while you're holding down the Ctrl key, say? Or only if you click an "inspector" checkbox? I think it's important to be able to play Lee's pong shader game. :-) 

Not sure about the the magnification yet. If it's not functional, let's at least hide it from the UI for now.

**Comment by lgritz** [comment]
On both OSX and Linux, when I build this, I can see the pixel zoom, but there's no visible text?

**Comment by marsupial** [comment]
Some times one can just fall in love with Qt

**Comment by lgritz** [comment]
OK, LGTM for now. I may tinker with the UI when I add some other changes on top of it that I am in the middle of. Have some more interesting features coming.

**Comment by marsupial** [comment]
Tinker away.  If not obvious, as it is, stashing the Magnifier in a RenderView was easiest, but if not was envisioning possibly multiple RenderViews in which case it should probably have a home in the Main Window.

**Pull request merged**
