### PR TITLE
Added various OSL_MAYBE_UNUSED to make compiler builds happy.

### PR DESCRIPTION
**Pull request by lgritz**
From Alex Wells

### CODE REVIEW

**Comment by fpsunflower** [comment]
Why is this needed? Is it because some asserts go away entirely in some compilation modes?

**Comment by AlexMWells** [comment]
Some compilers (don't ask my which) were complaining of unused variables.  And yes they were unused because OSL_DASSERT(STUFF) doesn't emit stuff when in profile/release builds

**Comment by lgritz** [comment]
I've seen that problem, too (maybe on the OIIO side for analogous reasons) when experimenting with even more pedantic warning levels.

**Comment by fpsunflower** [comment]
Defining `DASSERT(expr)` as `(void) sizeof(expr)` was an attempt at "fixing" this -- but I guess some compilers are smart enough to notice that isn't a real use of the expression.

LGTM

**Pull request merged**
