### PR TITLE
Build against Cuda-11.0.1 and Optix 7.1

### PR DESCRIPTION
**Pull request by marsupial**
WIP:
I'm still having issues with the test-suite.
Running the tests individually/explicitly seems to pass, but if I run via **_ctest_** some shader's won't load.

### CODE REVIEW

**Comment by lgritz** [comment]
Where are you on this, @marsupial? It's still marked as a draft/WIP.

**Comment by marsupial** [comment]
Barely touched it in two weeks, though did get the pure-optix tests passing.
Going to revisit _testshade_ and _testrender_ tomorrow, which are probably failing from my naive changes for 7.1.

**Comment by lgritz** [comment]
ok, just wanted to be sure I wasn't the one holding it up

**Comment by marsupial** [comment]
So tried a bunch of builds and this is what I've found:
Bumping past to Cuda 10.0 breaks _transformc_
Optix7 has some breakage in general that seems unrelated to this PR.
Running the testsuite for Optix7 is requiring LD_LIBRARY_PATH, as nvrtc isn't finding _libnvrtc-builtins.so_.
It's hard to tell if thats internally from _nvrtcCreateProgram_, or from libnvrtc.so complaining.
Also hard to tell whether that this lib needs to be installed at the sytem-level here.
(Tried a bunch of standard linker-type flags to _nvrtcCreateProgram_ to give a hint, but it accepted none of them.

---
Optix 6.0 Cuda 10 & 11.0.1
All passing

---

Optix 7.0 Cuda 10.0
The following tests FAILED:
     24 - blendmath.optix (Failed)
     25 - blendmath.optix.opt (Failed)
     58 - color.optix (Failed)
    206 - named-components.optix (Failed)
    207 - named-components.optix.opt (Failed)
    435 - testoptix-noise.optix.opt (Failed)

---

Optix 7.0 Cuda 10.1
The following tests FAILED:
     24 - blendmath.optix (Failed)
     25 - blendmath.optix.opt (Failed)
     58 - color.optix (Failed)
    206 - named-components.optix (Failed)
    207 - named-components.optix.opt (Failed)
    402 - transformc.optix (Failed)
    403 - transformc.optix.opt (Failed)
    435 - testoptix-noise.optix.opt (Failed)

---

Optix 7.1 Cuda 11.0.1
The following tests FAILED:
     24 - blendmath.optix (Failed)
     25 - blendmath.optix.opt (Failed)
     58 - color.optix (Failed)
    206 - named-components.optix (Failed)
    207 - named-components.optix.opt (Failed)
    402 - transformc.optix (Failed)
    403 - transformc.optix.opt (Failed)
    435 - testoptix-noise.optix.opt (Failed)

**Comment by lgritz** [comment]
What's the current status on these, @marsupial ? Did the stack size patch fix everything?

**Comment by marsupial** [comment]
Yes, everything passing now.
Still needed to add LD_LIBRARY_PATH to point to CUDA so libnvrtc-builtins.so can be loaded.
https://github.com/imageworks/OpenShadingLanguage/blob/fc21d425cc04ad9365e10618ea83207c1792ecae/CMakeLists.txt#L320

**Comment by lgritz** [comment]
Does this look ok to you, @cmstein ?

**Comment by cmstein** [comment]
Yes, LGTM!

**Pull request merged**
