### PR TITLE
Allow functions to return a struct.

### PR DESCRIPTION
**Pull request by lgritz**

### CODE REVIEW

**Comment by lgritz** [comment]
Fixes #233

**Comment by fpsunflower** [comment]
LGTM

Are there any subtleties around nested structs or arrays that would warrant a few more tests?

**Comment by lgritz** [comment]
Probably. I'll set up a test for that.

**Comment by lgritz** [comment]
Added a complicated test with structs of structs, arrays in structs, arrays of structs in structs.

Believe it or not, it ran correctly the first time!

**Comment by fpsunflower** [comment]
Nice!

**Pull request merged**
