### PR TITLE
Fix array initialization counter

### PR DESCRIPTION
**Pull request by marsupial**
## Description
Fixes the the element count checking that occurs when initializing an array.

## Tests
Added oslc-err-initlist

### CODE REVIEW

**Comment by lgritz** [comment]
Oh, so the checks were there, but it was just an off-by-one error?

**Comment by marsupial** [comment]
Yeah, curios if there's any obvious cases I'm missing to test further?

**Comment by lgritz** [comment]
LGTM. I'll merge as soon as the CI tests are finished.

I don't suppose you already tried on your side to build the SPI shading library against this, just to see if the previous failure to find this error had let bugs creep into it?

**Comment by marsupial** [comment]
Built the library yes, haven't run the test suite (was hoping to do it overnight).
As it caught no hidden errors, would be shocked if it changed any behavior.

**Comment by lgritz** [comment]
Yeah, I don't expect any change to runtime. If it doesn't come up with new errors when compiling (i.e., errors missed before), I think you're home free. So I'll merge. If anything goes wrong, we can fix.

**Pull request merged**
