### PR TITLE
testshade: allow OSL code snippets in place of shaders.

### PR DESCRIPTION
**Pull request by lgritz**
Basically, this experimental feature allows you to use testshade in such a way that instead of specifying shaders on disk, to be able to specify a little bit of OSL code on the command line itself, which will be automatically embedded into a shader boilerplate:

    shader <automatically-generated-shadername> (
        float s = u [[ int lockgeom=0 ]],
        float t = v [[ int lockgeom=0 ]],
        output color result = 0,
        output float alpha = 1)
    {
        <the code goes here>
    }

This is assembled, compiled (in memory!) on the fly, and then treated just like any other layer you might have specified to be read from disk.

Your expression presumably sets 'result', and the point is to save result to an image file, with resolution specified on the command line. As always, testshade sets u and v to go from 0->1 across the resulting image.

Here's a simple use to make a color gradient across the image:

    testshade -g 512 512 --expr "result = color(u, v, 0);" -o result out.exr

You can do anything that's valid in OSL, like this texture lookup that effectively acts as a filtered rescale of the source image:

    testshade -g 512 512 --expr "result = texture(\"input.exr\", u, v\");" -o result out.exr

Or this noise pattern, an fBm loop:

    testshade --expr "int octaves = 6; float amp = 0.5, freq=5; for (int i = 0; i < octaves; ++i, freq *= 2, amp *= 0.5) result += amp * ((float)snoise(s*freq,t*freq)); result += 0.5;" -g 640 480 -o result out.exr

### CODE REVIEW

**Comment by lgritz** [comment]
That last example didn't show up well, did it? I'll try it again here, reformatted for clarity:

    testshade --expr "int octaves = 6; float amp = 0.5, freq=5; \
                      for (int i = 0; i < octaves; ++i, freq *= 2, amp *= 0.5) \
                          result += amp * ((float)snoise(s*freq,t*freq)); \
                      result += 0.5;" \
             -g 640 480 -o result out.exr

**Comment by lgritz** [comment]
Haha, so much fun. Edge detector in OSL using derivatives:

    testshade --expr 'float f = luminance(texture("grid.tx",s,t)); \
                      result = 0.5 + color(Dx(f), Dy(f), 0);' \
             -g 512 512 -o result gradient.exr

**Comment by aconty** [comment]
LGTM -- Neat!

**Comment by danwexler** [comment]
You realize, of course, that this eases the path to domination for our
robot overlords?

**Comment by fpsunflower** [comment]
LGTM2 :+1: 

Any thoughts on making this available directly from `liboslexec` ?

**Comment by lgritz** [comment]
Thoughts, oh my, yes.

Dan, I am aware of that, but this is mere tomfoolery. Friday is dedicated to WMD's. I'm just teeing some things up now.

**Comment by lgritz** [comment]
I also added a unit test.

**Pull request merged**
