### PR TITLE
`#pragma nowarn` suppresses warning on the following source line.

### PR DESCRIPTION
**Pull request by lgritz**

### CODE REVIEW

**Comment by marsupial** [comment]
I'd really like for some headers in the future to be shared between OSL and C++ and using a namespace allows for less conflicts and more obvious warnings over them (i.e. I see a **huge** benefit in setting the precedent to do this):

`#pragma osl nowarn` or `#pragma osl(nowarn)`

**Comment by lgritz** [comment]
I'm not sure how big is the subset is of functions that are useful and identically expressed in both language.

But I totally can get behind your rationale and am happy to change the syntax.  

I think I'm leaning toward your first suggestion, `#pragma osl blah`

**Comment by lgritz** [comment]
Pushed an update. Now it's

    #pragma osl nowarn

Good suggestion.

**Comment by fpsunflower** [comment]
LGTM

**Pull request merged**
