### PR TITLE
Add "or", "and" and "not" as synonyms to "&&", "||" and "!".

### PR DESCRIPTION
**Pull request by ssteinbach**
From this discussion:
https://groups.google.com/forum/#!topic/osl-dev/nds648OuPvM

### CODE REVIEW

**Comment by ssteinbach** [comment]
Hi Larry, CLA should be all clear now.  Let me know if you need anything else from me!

**Comment by lgritz** [comment]
Squashed your checkins into just one commit, amended the OSL language spec to explain the new keywords, and... MERGED!

I sure hope nobody has been using 'and', 'or', or 'not' as variable names.

**Comment by lgritz** [comment]
This was merged, by the way.

**Comment by ssteinbach** [comment]
Cool, Thanks!  I also submitted the “allow trailing commas” pull request.  Let me know if that one needs any fixes or cleanup!

**Pull request closed without merging**
