### PR TITLE
OpenShadingLanguage/master: Change to GNUInstallDirs for install paths

### PR DESCRIPTION
**Pull request by dracwyrm**
The variables: BIN_INSTALL_DIR, LIB_INSTALL_DIR, INCLUDE_INSTALL_DIR,
DOC_INSTALL_DIR, and MAN_INSTALL_DIR are defined but never used.
Instead, hard coded paths to lib, include, and bin were used. This
will cause difficulty on multi-lib systems or in cases where they
are named differently. The existing variables were replaced by the
GNUInstallDirs variables, which is compatible on all systems.

There were two instances of the install_targets macro defined, so
removed one and upgraded it to use GNUInstallDirs. Also, it was
never used in code, so all library installs were changed to use it.
Thus all library installs now use GNUInstallDirs.

INSTALL_DOCS variable is defined, so it's now controlling if
the documentation is being installed.

Signed-off by: Jonathan Scruggs <j.scruggs@gmail.com>

Please Note: This is a port of the code I modified from the RB-1.8 branch and did a full install test of that branch.

- [X] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [X] I have previously submitted a [Contributor License Agreement](http://opensource.imageworks.com/cla/).
- [ ] I have updated the documentation, if applicable.
- [ ] I have ensured that the change is tested somewhere in the testsuite (adding new test cases if necessary).
- [X] My code follows the prevailing code style of this project.

From the 1.8 branch test install:
Installed files when set to no docs (note: gentoo installs readme by default) and no tests:
```
/usr
/usr/bin
/usr/bin/oslc
/usr/bin/oslinfo
/usr/include
/usr/include/OSL
/usr/include/OSL/Imathx.h
/usr/include/OSL/accum.h
/usr/include/OSL/dual.h
/usr/include/OSL/dual_vec.h
/usr/include/OSL/export.h
/usr/include/OSL/genclosure.h
/usr/include/OSL/llvm_util.h
/usr/include/OSL/matrix22.h
/usr/include/OSL/optautomata.h
/usr/include/OSL/oslclosure.h
/usr/include/OSL/oslcomp.h
/usr/include/OSL/oslconfig.h
/usr/include/OSL/oslexec.h
/usr/include/OSL/oslnoise.h
/usr/include/OSL/oslquery.h
/usr/include/OSL/oslversion.h
/usr/include/OSL/rendererservices.h
/usr/include/OSL/shaderglobals.h
/usr/lib64
/usr/lib64/liboslcomp.so
/usr/lib64/liboslexec.so
/usr/lib64/liboslnoise.so
/usr/lib64/liboslquery.so
/usr/lib64/osl.imageio.so
/usr/shaders
/usr/shaders/emitter.osl
/usr/shaders/emitter.oso
/usr/shaders/glass.osl
/usr/shaders/glass.oso
/usr/shaders/image.osl
/usr/shaders/image.oso
/usr/shaders/matte.osl
/usr/shaders/matte.oso
/usr/shaders/metal.osl
/usr/shaders/metal.oso
/usr/shaders/oslutil.h
/usr/shaders/stdosl.h
/usr/shaders/ubersurface.osl
/usr/shaders/ubersurface.oso
/usr/share
/usr/share/doc
/usr/share/doc/osl-1.8.10
/usr/share/doc/osl-1.8.10/README.md.bz2
```

### CODE REVIEW

**Comment by dracwyrm** [comment]
Why did this fail all the builds? The correct directories are being returned. I added message outputs in the RB-1.8 version and it shows this:
-- CMAKE_INSTALL_PREFIX is /home/travis/build/imageworks/OpenShadingLanguage/dist/linux64.debug
-- CMAKE_INSTALL_LIBDIR is lib
-- CMAKE_INSTALL_BINDIR is bin
-- CMAKE_INSTALL_DOCDIR is share/doc/OSL

When you look at the diff, it's all like for like... except docs.

**Comment by lgritz** [comment]
Oh, I was not aware of the GNUInstallDirs. Nice. I'll give this a try, it's a nice simplification if it works.

Does everything work as expected on Windows? (I have no easy way to test that myself.)

Does it correctly make the python vs python3 directory distinction?

**Comment by lgritz** [comment]
Ah, I see, there isn't a python module for OSL at this time. So 1/2 never mind.

But the other 1/2 -- what will we need to do to support Python modules in the future? The reason that complexity was here is that this section of the build scripts is just copied between the OIIO and OSL projects, and there is some utility in keeping them in sync (makes my life easier, for one thing). So I want to make sure that this solution can be propagated to the OIIO project as well without breaking something there.

**Comment by dracwyrm** [comment]
@lgritz I noticed there were no python modules, but the variables were defined for it. Python is one of those tricky directories as each distribution seems to have their own structure, for example, on Gentoo: /usr/lib64/python3.5/site-packages/. The only way to do that is to have a variable that package managers can set. A default could be ${CMAKE_INSTALL_LIBDIR}/python3/site-packages. On Gentoo, we have tools that can define things during the configure phase that gets the site directory.

I haven't looked at OIIO yet as it's installing to lib64 for now, but it should be able to be done. I have submitted a PR for OpenEXR already, and have some lined up for OpenVDB, ctl, and OpenSubDiv. I could look at OIIO and do a switch over for it, as it does remove a lot of code and the paths remain overridable. It's illegal now on Gentoo to install to /usr/lib, it must be lib64 or lib32 for multilib systems. GNUInstallDirs handles all that for us.

I was told that GNUInstallDirs is usable on Windows.
More info here:
https://cmake.org/cmake/help/v3.4/module/GNUInstallDirs.html

Thanks for taking the time to look at this PR.

**Comment by SoapGentoo** [comment]
@lgritz handling python in CMake has historically been bad, so there's not a lot of involvement with `GNUInstallDirs` here.

But please merge `GNUInstallDirs`, it's an important part for making the CMake-based ecosystem as uniform as possible. All distributions have hooks for the `GNUInstallDirs` variables.

**Comment by lgritz** [comment]
Do you stand by this review in its current form, or do you want to do a pass on it to compare to what we ended up with on the OIIO side and make sure they match?

**Comment by dracwyrm** [comment]
@lgritz I will do a compare with the OIIO code. I want them to be as similar as possible. A lot of great changes were done. :)

**Comment by dracwyrm** [comment]
@lgritz Just cleaned up the a few things to better match oiio. :) Now for a new round of checks.

**Comment by lgritz** [comment]
LGTM. Just waiting for CI tests and I'll give it a try myself. If all pans out, I'll merge it.

**Comment by lgritz** [comment]
Tests all pass. Merging.

**Pull request merged**
