### PR TITLE
Allow trailing commas 

### PR DESCRIPTION
**Pull request by ssteinbach**
...in function argument, shader argument, and metadata lists.  From:

https://groups.google.com/forum/#!topic/osl-dev/swRNU97n16Y

### CODE REVIEW

**Comment by ssteinbach** [comment]
Like I said in the other thread, CLA should be all good to go.  Thanks for your patience!

**Comment by lgritz** [comment]
Yes, that's what I hear! I will test and merge.

**Comment by ssteinbach** [comment]
Awesome. Let me know if you see anything.

**Comment by ssteinbach** [comment]
This is also good to go now that the CLA is all good. Thanks!

**Comment by lgritz** [comment]
Squashed and merged! Thanks for the patch!

**Pull request closed without merging**
