### PR TITLE
Added mission statement in the charter, pulled from README

### PR DESCRIPTION
**Pull request by jmertic**
We've tended to have projects embed the mission statement in the charter lately, so pulling what was in the README to add here.

Signed-off-by: John Mertic <jmertic@linuxfoundation.org>

### CODE REVIEW

**Review by lgritz — APPROVED** [review]
LGTM, but as a change to the charter, I guess we need to vote on it at the next meeting?

**Comment by jmertic** [comment]
I'd recommend that @lgritz - I can be on that call if it's helpful.

**Comment by lgritz** [comment]
I'm sure we can handle it, we'll just do it at next week's TSC meeting.

**Comment by jmertic** [comment]
Sounds good - keep me posted

**Comment by lgritz** [comment]
Approved by the TSC by vote on 2020-12-10

**Review by lgritz — APPROVED** [review]
Approved by the TSC by vote on 2020-12-10

**Comment by jmertic** [comment]
Thank you Larry - having the series agreement filed now.

**Pull request merged**
