### PR TITLE
Move matrix transform shadeops out of llvm_ops and into opmatrix

### PR DESCRIPTION
**Pull request by fpsunflower**
This has the side benefit of avoiding the Imath exception handling in matrix inverse from making it into the bit code LLVM needs to process, reducing the amount of runtime symbol resolution required.

This also avoids some code duplication we had between these two files.

### CODE REVIEW

**Comment by fpsunflower** [comment]
Oops, clearly something broke - this isn't passing the tests.

**Comment by lgritz** [comment]
Don't worry if the CI test fails on OSX, that's a Travis issue I need to work out. But all the Linux tests should pass.

**Comment by fpsunflower** [comment]
Bad copy-paste. This one should be good.

**Comment by lgritz** [comment]
Still seems to be failing testsuite/vector in the CI tests

**Comment by fpsunflower** [comment]
One more time ...

(I had forgotten to move out the declaration out of the bitcode portion, which only the `vector` test covered)

**Comment by fpsunflower** [comment]
All tests are passing now (minus the os x ones).

**Comment by lgritz** [comment]
I'm testing on my end now, will merge if it passes.

**Comment by lgritz** [comment]
LGTM! Merging.

**Pull request merged**
